# kuri Theme Config @ version 1.0.0
# website: https://kuri.ink | cl@kuri.ink

# Yourself / 个人信息
nickname:  # 昵称
motto:  # 一句话简介
logo:  # 头像
github:  # Github 个人主页地址
background: # 背景图片
  - https://api.ee123.net/img/bingimg/dayimg.jpg
iconfont: /css/iconfont.css

# SEO / 搜索引擎优化
fav: /images/fav.png

# Sidebar / 侧边栏
sidebar: {}

sidebar_color: {}

# Header / 页眉信息
chizaobook: true # true / false 在页眉显示摛藻好句功能

# Social / 社交按钮
social:
  

# Footer / 页脚信息
## copyright / 版权
author:  # 作者名称
## remark / 备注
remark: ''
## Regist / 备案
regist: ''

# tools / 工具
analysis: 
  platform: 51.la
  id: 
  cd: 
aplayer: 
  enable: false
  platform: 
  type: 
  id: 
  fixed: true
